# Generated by Django 5.1.3 on 2024-12-12 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('url', models.URLField(verbose_name='URL')),
                ('version', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='Version')),
                ('etag', models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='ETag')),
                ('file', models.FileField(blank=True, null=True, upload_to='schedule/', verbose_name='File')),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'default_related_name': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleView',
            fields=[
                ('baseview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseview')),
                ('room_filter', models.CharField(blank=True, help_text='Room filter for schedule as semicolon-separated list', max_length=256, null=True, verbose_name='Room Filter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Schedule View',
                'verbose_name_plural': 'Schedule Views',
                'default_related_name': 'schedule_views',
            },
            bases=('core.baseview',),
        ),
    ]
